[package]
name = "evm-precompile-zkcard"
version = "0.1.0"
authors = ["FindoraNetwork"]
edition = "2021"
homepage = "https://findora.org/technology"
repository = "https://github.com/findoranetwork/platform/"
description = "ZKCARD precompiles for EVM module."
readme = "README.md"

[dependencies]
ethereum-types = { version = "0.13.1", default-features = false }
evm = { version = "0.35.0", default-features = false, features = ["with-serde"] }
evm-precompile-utils = { path = "../utils"}
fp-traits = { path = "../../../../primitives/traits" }
tracing = "0.1"
module-evm = { path = "../../../../modules/evm"}
num_enum = { version = "0.5.4", default-features = false }
slices = "0.2.0"
config = { path = "../../../../../config" }
num = { version = "0.3", features = ["alloc"] }
starknet-curve = { git = "https://github.com/geometryresearch/proof-toolbox.git", branch = "fix/schnorr_affine" }
barnett-smart-card-protocol = { git = "https://github.com/FindoraNetwork/mental-poker.git", branch = "mercury-serialize-error-fix" }
ark-serialize = "0.3.0"
proof-essentials = { git = "https://github.com/HarryLiIsMe/findora-proof-toolbox.git", branch = "findora" }
ark-ec = "0.3.0"
rand = "0.8"
ark-std = { version = "0.3.0", features = ["std"] }

[dev-dependencies]
baseapp = { path = "../../../../baseapp" }
fp-mocks = { path = "../../../../primitives/mocks" }
sha3 = "0.10"