[package]
name = "rust-locust"
version = "0.1.0"
authors = ["Brian Rogoff <brian@findora.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
credentials = { path = "../../libs/credentials" }
hex = "0.4.2"
pyo3 = { version = "0.9.2", features = ["extension-module"] }
rayon = "1.0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
rand_core = { version = "0.5", default-features = false, features = ["alloc"] }
rand_chacha = "0.2.0"
txn_builder = { path = "../txn_builder" }
wasm-bindgen = { version = "0.2.50", features = ["serde-serialize"]  }
zei = { git = "ssh://git@github.com/findoraorg/zei", tag = "v0.0.2-4" }

[lib]
name = "rust_locust"
crate-type = ["cdylib"]
