FROM debian:11.0-slim
ENV WORK_DIR /platform
ENV WASM_DIR /tmp/wasm-js-bindings

COPY binary/goleveldb/findorad /usr/local/sbin/findorad
COPY container/docker-entrypoint-findorad.sh /docker-entrypoint.sh
WORKDIR /
ENTRYPOINT ["/docker-entrypoint.sh"]
