FROM clux/muslrust

RUN git clone https://github.com/tpoechtrager/osxcross /opt/osxcross
ENV WORK_DIR /opt/osxcross
WORKDIR $WORK_DIR
ENV OPENSSL_DIR /musl

RUN rustup target add x86_64-apple-darwin
RUN echo "[target.x86_64-apple-darwin]\nlinker = "x86_64-apple-darwin14-clang"\nar = "x86_64-apple-darwin14-ar"" >> ~/.cargo/config

