FROM binary-rust-base
ENV WORK_DIR /platform
ENV WASM_DIR /tmp/wasm-js-bindings
ENV VERGEN_SHA_EXTERN release_build
ENV PATH=$PATH:/root/.cargo/bin/

COPY . $WORK_DIR
WORKDIR $WORK_DIR

RUN ALL_PROXY=http://10.10.11.251:7890 apt-get install -y procps

RUN rustup toolchain install stable && \
    rustup component add clippy --toolchain stable && \
    rustup component add rustfmt

RUN mkdir -p /root/.cargo/bin/ && make debug_env

RUN printf "./tools/devnet/startnodes.sh\ntail -f /tmp/findora/devnet/node0/consensus.log" > docker_debug_env.sh
RUN chmod +x docker_debug_env.sh
CMD ["sh","-c","./docker_debug_env.sh"]
