FROM ubuntu:20.04
RUN apt update && apt install libleveldb-dev curl wget perl jq -y
RUN apt install net-tools iputils-ping telnet -y
RUN apt install python3-pip -y && pip install toml-cli
ENV PATH="/root/.findora_bin:${PATH}"
COPY scripts/start_local_validator_testnet.sh /usr/local/bin/init_testnet.sh
COPY scripts/start_local_validator_qa01.sh /usr/local/bin/init.sh
COPY scripts/restart_local_validator.sh /usr/local/bin/restart.sh
WORKDIR /root
ENTRYPOINT ["/bin/bash"]
