[package]
name = "whitelist"
version = "0.1.0"
authors = ["Engineering <engineering@findora.org>"]
edition = "2018"

[lib]
path = "src/whitelist.rs"

[dependencies]
curve25519-dalek = { version =  "2.0.0", features = ["serde"] }
ledger = { path = "../../ledger" }
ledger_standalone = { path = "../ledger_standalone" }
rand_chacha = "0.2"
rand_core = { version = "0.5", default-features = false, features = ["alloc"] }
serde = { version = "1.0.99", features = ["derive"] }
serde_json = "1.0"
txn_builder = { path = "../txn_builder" }
txn_cli = { path = "../txn_cli" }
zei = { git = "ssh://git@github.com/findoraorg/zei", tag = "v0.0.2-4" }
