[package]
name = "whitelist"
version = "0.1.0"
authors = ["Engineering <engineering@findora.org>"]
edition = "2018"

[lib]
path = "src/whitelist.rs"

[dependencies]
bulletproofs = { version = "2.0.0",  package = "bulletproofs", git = "https://github.com/dalek-cryptography/bulletproofs", rev = "91218d4066af5d582631319c5ff0266402b9fff2", features = ["yoloproofs"]}
curve25519-dalek = { version =  "2.0.0", features = ["serde"] }
ledger = { path = "../../ledger" }
ledger_standalone = { path = "../ledger_standalone" }
rand_chacha = "0.2"
rand_core = { version = "0.5", default-features = false, features = ["alloc"] }
serde_json = "1.0"
txn_builder = { path = "../txn_builder" }
txn_cli = { path = "../txn_cli" }
zei = { path = "/Users/keyaoshen/code/zei"}
