[package]
name = "http_tester"
version = "0.1.0"
authors = ["Brian Rogoff <brian@findora.org>"]
edition = "2018"

[dependencies]
ruc = { git = "https://github.com/FindoraNetwork/RUC.git", branch = "master" }
air = { path = "../../../libs/ads/air" }
clap = "2.33.0"
credentials = { path = "../../../libs/credentials" }
cryptohash = { path = "../../../libs/cryptohash" }
env_logger = "0.8.3"
ledger = { path = "../../../ledger" }
log = "0.4.8"
rand_chacha = "0.2.0"
rand_core = { version = "0.5", default-features = false, features = ["alloc"] }
attohttpc = { version = "0.16.3", default-features = false, features = ["compress", "json", "tls-rustls"] }
serde = { version = "1.0.124", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0.40"
time = "0.2.15"
txn_builder = { path = "../../txn_builder" }
utils = { path = "../../../libs/utils" }
zei = { git = "ssh://git@github.com/FindoraNetwork/zei", tag = "v0.1.1" }
