[package]
name = "platform"
version = "0.1.0"
authors = ["Nathan Yospe <nathan@eian.io>"]
edition = "2018"

[dependencies]
abci = "0.4.3"
actix = "0.8.3"
arrayref = "0.3.5"
clap = "2.33.0"
dirs = "2.0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
rand_chacha = "0.1.1"
rand = "0.6"

zei = { git = "ssh://github.com/eianio/zei", branch="feature/serde_json_byte_arrays" }

core = {path = "core"}
txn_builder = {path = "components/txn_builder"}
ledger_app = {path = "components/ledger_app"}
scp_validator_node = {path = "scp_validator_node"}
