[package]
name = "platform"
version = "0.1.0"
authors = ["Nathan Yospe <nathan@eian.io>"]
edition = "2018"

[dependencies]
abci = "0.4.3"
actix-web = "1.0"
arrayref = "0.3.5"
clap = "2.33.0"
dirs = "2.0.1"
findora = { path = "findora" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
rand_chacha = "0.1.1"
rand = "0.6"
regex = "1"

zei = { git = "ssh://github.com/findoraorg/zei" }

ledger = {path = "ledger"}
txn_builder = {path = "components/txn_builder"}
ledger_app = {path = "components/ledger_app"}
api_service = {path = "components/api_service"}

