[package]
name = "ledger_module"
version = "0.1.0"
authors = ["Nathan Yospe <nathan@eian.io>, Kevin Foley <kevin@eian.io>"]
edition = "2018"

[dependencies]
abci = "0.4.3"
chrono = "0.4"
schnorr = "0.0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
blake2 = "0.8.0"
zei = {git = "ssh://github.com/eianio/zei", branch = "ledger"}
