[workspace]
members = [
    "src/ledger",
    "src/components/finutils",
    "src/components/abciapp",
    "src/components/wasm",
    "src/components/frog",
    "src/libs/bitmap",
    "src/libs/merkle_tree",
    "src/libs/globutils",
    "src/libs/cryptohash",
    "src/libs/credentials",
    "src/libs/sliding_set",
]

[profile.dev]
incremental = false
overflow-checks = true

[profile.release]
incremental = false
overflow-checks = false

[profile.bench]
codegen-units = 1
overflow-checks = false

[profile.dev.package.curve25519-dalek]
opt-level = 1
overflow-checks = false
