[workspace]
members = [
    "components/abci_validator_node",
    "components/address_identity_registry",
    "components/account_simulator",
    "components/ledger_api_service",
    "components/client",
    "components/check_merkle",
    "components/ledger_client",
    "components/ledger_standalone",
    "components/ledger_mirror",
    "components/submission_api",
    "components/submission_server",
    "components/txn_builder",
    "components/txn_builder_cli",
    "components/query_api",
    "components/query_server",
    "components/wasm",
    "findora",
    "ledger",
    "libs/ads/air",
    "libs/ads/merkle_tree",
    "libs/ads/sparse_merkle_tree",
    "libs/bitmap",
    "libs/cryptohash",
]
