[workspace]
members = [
    "components/abci_validator_node",
    "components/address_identity_registry",
    "components/account_simulator",
    "components/auditor",
    "components/xfrnote",
    "components/ledger_api_service",
    "components/check_merkle",
    "components/ledger_client",
    "components/ledger_standalone",
    "components/ledger_mirror",
    "components/log_tester",
    "components/solvency",
    "components/solvency_cli",
    "components/submission_api",
    "components/submission_server",
    "components/txn_builder",
    "components/txn_cli",
    "components/query_api",
    "components/query_server",
    "components/wasm",
    "components/whitelist",
    "findora",
    "ledger",
    "libs/ads/air",
    "libs/ads/merkle_tree",
    "libs/ads/sparse_merkle_tree",
    "libs/bitmap",
    "libs/cryptohash",
    "libs/credentials",
    "libs/utils",
]
