[workspace]
members = [
    "components/abci_validator_node",
    "components/ac_test_cli",
    "components/account_simulator",
    "components/ledger_api_service",
    "components/chat",
    "components/check_merkle",
    "components/ledger_client",
    "components/ledger_standalone",
    "components/submission_api",
    "components/submission_server",
    "components/txn_builder",
    "components/txn_builder_cli",
    "components/wasm",
    "findora",
    "ledger",
    "libs/ads/merkle_tree",
    "libs/ads/sparse_merkle_tree",
    "libs/bitmap",
    "libs/cryptohash",
]
