[package]
name = "platform"
version = "0.1.0"
authors = ["Engineering <engineering@findora.org>"]
edition = "2018"

[workspace]
members = [
    "components/abci_validator_node",
    "components/ac_test_cli",
    "components/account_simulator",
    "components/api_service",
    "components/api_service_standalone",
    "components/chat",
    "components/check_merkle",
    "components/ledger_app",
    "components/ledger_client",
    "components/ledger_standalone",
    "components/query_processor",
    "components/txn_builder",
    "components/txn_builder_cli",
    "components/wasm",
    "findora",
    "ledger",
]

[dependencies.rand]
version = "0.6"

features = ["stdweb", "wasm-bindgen"]
