[package]
name = "platform"
version = "0.1.0"
authors = ["Nathan Yospe <nathan@eian.io>"]
edition = "2018"

[dependencies]

core = {path = "core"}
txn_builder = {path = "components/txn_builder"}
ledger_app = {path = "components/ledger_app"}
abci_validator_node = {path = "abci_validator_node"}
scp_validator_node = {path = "scp_validator_node"}
eian_txn_builder = {path = "eian_txn_builder"}
