[workspace]
members = [
    "components/cli2",
    "components/abciapp",
    "components/ledger_api_service",
    "components/query_api",
    "components/query_server",
    "components/submission_api",
    "components/submission_server",
    "components/txn_builder",
    "components/wasm",
    "components/wallet",
    "components/fintools",
    "ledger",
    "libs/ads/air",
    "libs/ads/merkle_tree",
    "libs/ads/sparse_merkle_tree",
    "libs/bitmap",
    "libs/cryptohash",
    "libs/credentials",
    "libs/sliding_set",
    "libs/utils",
]

[profile.dev]
incremental = false
overflow-checks = true

[profile.release]
incremental = false
overflow-checks = false

[profile.bench]
codegen-units = 1
overflow-checks = false

[profile.dev.package.curve25519-dalek]
opt-level = 1
overflow-checks = false
