[workspace]
members = [
    "components/abci_validator_node",
    "components/address_identity_registry",
    "components/account_simulator",
    "components/auditor",
    "components/check_merkle",
    "components/http_tester",
    "components/ledger_api_service",
    "components/ledger_client",
    "components/ledger_standalone",
    "components/ledger_mirror",
    "components/log_tester",
    "components/query_api",
    "components/query_server",
    "components/solvency",
    "components/solvency_cli",
    "components/submission_api",
    "components/submission_server",
    "components/txn_builder",
    "components/txn_cli",
    "components/wasm",
    "components/whitelist",
    "components/whitelist_cli",
    "components/xfrnote",
    "components/cli2",
    "components/wallet",
    "ledger",
    "libs/ads/air",
    "libs/ads/merkle_tree",
    "libs/ads/sparse_merkle_tree",
    "libs/bitmap",
    "libs/cryptohash",
    "libs/credentials",
    "libs/sliding_set",
    "libs/network",
    "libs/utils",
]

[profile.dev]
incremental = true
overflow-checks = true

[profile.release]
codegen-units = 1
incremental = false
overflow-checks = false

[profile.bench]
codegen-units = 1
overflow-checks = false

[profile.dev.package.curve25519-dalek]
opt-level = 1
overflow-checks = false
