[package]
name = "check_merkle"
version = "0.1.0"
authors = ["Engineering <engineering@findora.org>"]
edition = "2018"

[[bin]]
name = "check_merkle"
path = "src/check_merkle.rs"

[dependencies]
ledger = { path = "../../ledger" }
findora = { path = "../../findora" }
merkle_tree = { path = "../../libs/ads/merkle_tree" }
<<<<<<< HEAD
zei = { git = "ssh://git@github.com/findoraorg/zei" }
=======
zei = { git = "ssh://git@github.com/findoraorg/zei", tag = "v0.0.2" }
>>>>>>> master
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dev-dependencies]
quickcheck = "0.8"
quickcheck_macros = "0.8"

