[package]
name = "evm-wasm-util"
version = "0.2.0"
authors = ["FindoraNetwork"]
edition = "2018"

description = ""
repository = ""
license = ""

# wasm-opt has a segfaulting issue. Disabling for now
[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[dependencies]
base64 = "0.10"
ethereum = { version = "0.9.0", default-features = false, features = ["with-serde"] }
ethereum-types = { version = "0.12", default-features = false }
fp-types = { path = "../../primitives/types" }
rlp = "0.5"
ruc = { git = "https://github.com/FindoraNetwork/RUC.git", branch = "master" }
sha3 = "0.8"
serde_json = "1.0"
wasm-bindgen = { version = "0.2.62", features = ["serde-serialize"] }

# Must enable the "js"-feature,
# OR the compiling will fail.
getrandom = { version = "0.2", features = ["js"] }

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/wasm.rs"
