[package]
name = "bugchecker"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "xx"
path = "src/bins/xx.rs"

[dependencies]
surf = { version = "2.3.1", default-features = false, features = ["h1-client-rustls"]}
async-std = "1.10.0"
parking_lot = "0.11.1"
rand = "0.8"
rand_chacha = "0.2.0"
lazy_static = "1.4.0"

zei = { git = "https://@github.com/FindoraNetwork/zei", branch = "develop" }
ruc = "0.6.2"

ledger = { path = "../../ledger" }
finutils = { path = "../finutils" }
globutils = { path = "../../libs/globutils" }
