[package]
name = "whitelist"
version = "0.1.0"
authors = ["Engineering <engineering@findora.org>"]
edition = "2018"

[lib]
path = "src/whitelist.rs"

[dependencies]
curve25519-dalek = { version =  "2.0.0", features = ["serde"] }
ledger = { path = "../../../ledger" }
ledger_standalone = { path = "../../ledger_standalone" }
network = { path = "../../../libs/network" }
rand_chacha = "0.2"
rand_core = { version = "0.5", default-features = false, features = ["alloc"] }
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0"
txn_builder = { path = "../../txn_builder" }
txn_cli = { path = "../../trash/txn_cli" }
ruc = { git = "https://github.com/FindoraNetwork/RUC.git", branch = "master" }
zei = { git = "ssh://git@github.com/FindoraNetwork/zei", tag = "v0.1.0d" }
