[package]
name = "module-evm"
version = "0.1.0"
authors = ["FindoraNetwork"]
edition = "2021"
homepage = "https://findora.org/technology"
repository = "https://github.com/findoranetwork/platform/"
description = "Findora module supporting evm smart contract"
readme = "README.md"

[dependencies]
abci = { git = "https://github.com/FindoraNetwork/tendermint-abci", tag = "0.7.6" }
ethereum-types = { version = "0.13.1", default-features = false }
evm = { version = "0.35.0", default-features = false, features = ["with-serde"] }
evm-runtime = { version = "0.35.0", default-features = false }
evm-gasometer = { version = "0.35.0", default-features = false }
ethereum = { version = "0.12.0", default-features = false, features = ["with-serde"] }
impl-trait-for-tuples = "0.2"
tracing = "0.1"
rlp = { version = "0.5", default-features = false }
ruc = "1.0"
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0.64"
sha3 = { version = "0.10", default-features = false }
hex = "0.4.3"
ethabi = "17.1.0"
zei = { package="platform-lib-noah", git = "https://github.com/FindoraNetwork/platform-lib-noah", branch = "develop" }
protobuf = "2.16"

# primitives, don't depend on any modules
fp-core = { path = "../../primitives/core" }
fp-evm = { path = "../../primitives/evm" }
fp-storage = { path = "../../primitives/storage" }
fp-traits = { path = "../../primitives/traits" }
fp-types = { path = "../../primitives/types" }
fp-utils = { path = "../../primitives/utils" }
config = { path = "../../../config"}
storage = { git = "https://github.com/FindoraNetwork/storage.git", tag = "v1.1.6" }
fin_db = { git = "https://github.com/FindoraNetwork/storage.git", tag = "v1.1.6" }
ledger = { path = "../../../../ledger" }
enterprise-web3 = { path = "../../primitives/enterprise-web3" }
module-ethereum = { path = "../ethereum" }

[dev-dependencies]
baseapp = { path = "../../baseapp" }
fp-mocks = { path = "../../primitives/mocks" }
hex = "0.4.3"
module-account = { path = "../account" }
serde_json = "1.0.64"

[features]
benchmark = []
