[package]
name = "module-evm"
version = "0.1.0"
authors = ["FindoraNetwork"]
edition = "2018"
homepage = "https://findora.org/technology"
repository = "https://github.com/findoranetwork/platform/"
description = "Findora module supporting evm smart contract"
readme = "README.md"

[dependencies]
abci = { git = "https://github.com/FindoraNetwork/rust-abci", tag = "v0.7.2" }
ethereum-types = { version = "0.12", default-features = false }
evm = { version = "0.30.0", default-features = false, features = ["with-serde"] }
evm-runtime = { version = "0.30.0", default-features = false }
evm-gasometer = { version = "0.30.0", default-features = false }
log = "0.4"
rlp = { version = "0.5", default-features = false }
ruc = { git = "https://github.com/FindoraNetwork/RUC.git", branch = "master" }
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0.64"
sha3 = { version = "0.8", default-features = false }

# primitives, don't depend on any modules
fp-core = { path = "../../primitives/core" }
fp-evm = { path = "../../primitives/evm" }
fp-storage = { path = "../../primitives/storage" }
fp-traits = { path = "../../primitives/traits" }
fp-types = { path = "../../primitives/types" }
fp-utils = { path = "../../primitives/utils" }

[dev-dependencies]
baseapp = { path = "../../baseapp" }
ethabi = { git = "https://github.com/rust-ethereum/ethabi.git", branch = "master" }
ethereum = { version = "0.9.0", default-features = false, features = ["with-serde"] }
fp-mocks = { path = "../../primitives/mocks" }
hex = "0.4.2"
module-account = { path = "../account" }
module-ethereum = { path = "../ethereum" }
serde_json = "1.0.64"
