[package]
name = "module-evm"
version = "0.1.0"
authors = ["Findora <admin@findora.org>"]
edition = "2018"
homepage = "https://findora.org/technology"
repository = "https://github.com/findoranetwork/platform/"
description = "Findora module supporting evm smart contract"
readme = "README.md"

[dependencies]
abci = { git = "https://github.com/FindoraNetwork/rust-abci", tag = "v0.7.2" }
ethereum-types = "0.11.0"
evm = { version = "0.27.0", features = ["with-serde"] }
evm-runtime = "0.27.0"
evm-gasometer = "0.27.0"
log = "0.4"
rlp = "0.5"
ruc = { git = "https://github.com/FindoraNetwork/RUC.git", branch = "master" }
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0.64"
sha3 = "0.8"

# primitives, don't depend on any modules
fp-core = { path = "../../primitives/core" }
fp-evm = { path = "../../primitives/evm" }
fp-storage = { path = "../../primitives/storage" }
fp-traits = { path = "../../primitives/traits" }
fp-types = { path = "../../primitives/types" }
fp-utils = { path = "../../primitives/utils" }

[dev-dependencies]
baseapp = { path = "../../baseapp" }
ethabi = "14.1.0"
ethereum = { version = "0.7.1", features = ["with-serde"] }
fp-mocks = { path = "../../primitives/mocks" }
hex = "0.4.2"
module-account = { path = "../account" }
module-ethereum = { path = "../ethereum" }
serde_json = "1.0.64"
