[package]
name = "abciapp"
version = "0.2.11"
authors = ["FindoraNetwork"]
build = "build.rs"
edition = "2021"

[[bin]]
name = "findorad"
path = "src/bins/findorad.rs"

[[bin]]
name = "abcid"
path = "src/bins/abcid.rs"

[dependencies]
parking_lot = "0.12"
base64 = "0.12"
bincode = "1.3.1"
log = "0.4.8"
rand = "0.8"
rand_chacha = "0.2"
rand_core = { version = "0.5", default-features = false, features = ["alloc"] }
attohttpc = { version = "0.23", default-features = false, features = ["compress", "json", "tls-rustls"] }
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0.40"
lazy_static = "1.4.0"
futures = { version = "0.3.16", features = ["thread-pool"] }
hex = "0.4.2"
ctrlc = { version = "3.0", features = ["termination"] }
protobuf = "2.16"
toml = "0.5.8"

clap = "2.33.3"

actix-cors = "0.5.4"
actix-rt = "1.1.0"
actix-service = "1.0.6"
actix-web = "3.3.2"
percent-encoding = "2.1.0"

nix = "0.22.1"

zei = { git = "https://github.com/FindoraNetwork/zei", branch = "stable-main" }
ruc = { version = "1.0.5", default-features = false, features = ["compact"] }
abci = { git = "https://github.com/FindoraNetwork/tendermint-abci", tag = "0.7.4" }
config = { path = "../config"}
ledger = { path = "../../ledger" }
cryptohash = { path = "../../libs/cryptohash" }
globutils = { path = "../../libs/globutils" }
finutils = { path = "../finutils" }

tempfile = "3.1.0"
baseapp = { path = "../contracts/baseapp" }
fc-rpc = { path = "../contracts/rpc" }
fp-storage = { path = "../contracts/primitives/storage" }
fp-utils = { path = "../contracts/primitives/utils" }


enterprise-web3 = { path = "../contracts/primitives/enterprise-web3", optional = true  }


[target.'cfg(target_os= "linux")'.dependencies]
btm = "0.1.6"

[dev-dependencies]

[build-dependencies]
vergen = "=3.1.0"

[features]
default = ["diskcache"]
diskcache = ["ledger/diskcache"]
debug_env = ["ledger/debug_env", "config/debug_env"]
web3_service = ["enterprise-web3", "baseapp/web3_service"]
benchmark = ["baseapp/benchmark"]
