[package]
name = "fp-events"
version = "0.1.0"
authors = ["FindoraNetwork"]
edition = "2021"
homepage = "https://findora.org/technology"
repository = "https://github.com/findoranetwork/platform/"
description = "Findora Primitive transaction events"
readme = "README.md"

[dependencies]
abci = { git = "https://github.com/FindoraNetwork/tendermint-abci", tag = "0.7.4" }
fp-event-derive = { path = "event-derive" }
protobuf = "2.16"
serde_json = "1.0"

[dev-dependencies]
serde = { version = "1.0.124", features = ["derive"] }
