[package]
name = "evm-precompile-basic"
version = "0.1.0"
authors = ["FindoraNetwork"]
edition = "2021"
homepage = "https://findora.org/technology"
repository = "https://github.com/findoranetwork/platform/"
description = "Basic precompiles for EVM module."
readme = "README.md"

[[bench]]
name = 'sha256'
path = 'benches/sha256.rs'
harness = false

[dependencies]
evm = { version = "0.35.0", default-features = false, features = ["with-serde"] }
module-evm = { path = "../../../../modules/evm"}
ripemd = "0.1"

# primitives
#fp-core = { path = "../../../../primitives/core" }
#fp-evm = { path = "../../../../primitives/evm" }
fp-types = { path = "../../../../primitives/types" }
fp-utils = { path = "../../../../primitives/utils" }