[package]
name = "evm-precompile-basic"
version = "0.1.0"
authors = ["Findora <admin@findora.org>"]
edition = "2018"
homepage = "https://findora.org/technology"
repository = "https://github.com/findoranetwork/platform/"
description = "Basic precompiles for EVM module."
readme = "README.md"

[dependencies]
evm = { version = "0.27.0", features = ["with-serde"] }
ripemd160 = "0.9"

# primitives
fp-core = { path = "../../../../primitives/core" }
fp-evm = { path = "../../../../primitives/evm" }
fp-types = { path = "../../../../primitives/types" }
fp-utils = { path = "../../../../primitives/utils" }