[package]
authors = ["FindoraNetwork"]
description = "Base application for tendermint abci"
edition = "2021"
homepage = "https://findora.org/technology"
name = "baseapp"
readme = "README.md"
repository = "https://github.com/findoranetwork/platform/"
version = "0.1.0"

[dependencies]
abci = "0.7.2"
ethereum = { version = "0.12.0", default-features = false, features = ["with-serde"] }
ethereum-types = { version = "0.13.1", default-features = false }
futures = "0.3.16"
lazy_static = "1.4.0"
ledger = {path = "../../../ledger"}
tracing = "0.1"
parking_lot = "0.12"
primitive-types = { version = "0.11.1", default-features = false, features = ["rlp", "byteorder", "serde"] }
protobuf = "2.16"
ruc = "1.0"
serde = {version = "1.0.124", features = ["derive"]}
serde_json = "1.0.40"
attohttpc = { version = "0.18", default-features = false, features = ["compress", "json", "tls-rustls"] }
base64 = "0.13"
once_cell = "1.10.0"
noah = { git = "https://github.com/FindoraNetwork/noah", tag = "v0.3.2" }
storage = { git = "https://github.com/FindoraNetwork/storage.git", tag = "v1.1.4" }
fin_db = { git = "https://github.com/FindoraNetwork/storage.git", tag = "v1.1.4" }
sha3 = "0.8"
hex = "*"

config = { path = "../../config"}

# primitives
fp-core = {path = "../primitives/core"}
fp-evm = {path = "../primitives/evm"}
fp-traits = {path = "../primitives/traits"}
fp-types = {path = "../primitives/types"}
fp-utils = {path = "../primitives/utils"}
enterprise-web3 = { path = "../primitives/enterprise-web3", optional = true  }

# modules
module-account = {path = "../modules/account"}
module-ethereum = {path = "../modules/ethereum"}
module-evm = {path = "../modules/evm"}
module-template = {path = "../modules/template"}
module-xhub = {path = "../modules/xhub"}

evm-precompile-basic = { path = "../modules/evm/precompile/basic" }
evm-precompile-frc20 = { path = "../modules/evm/precompile/frc20" }
evm-precompile-modexp = { path = "../modules/evm/precompile/modexp" }
evm-precompile-sha3fips = { path = "../modules/evm/precompile/sha3fips" }
evm-precompile-eth-pairings = { path = "../modules/evm/precompile/eth-pairings" }
evm-precompile = {path = "../modules/evm/precompile"}


[features]
abci_mock = []
web3_service = ["enterprise-web3", "module-account/web3_service", "module-ethereum/web3_service", "module-evm/web3_service"]
debug_env = []
