[package]
name = "ledger_standalone"
version = "0.1.0"
authors = ["Engineering <engineering@findora.org>"]
edition = "2018"

[[bin]]
name = "ledger_standalone"
path = "src/ledger_standalone.rs"

[dependencies]
api_service = { path = "../api_service" }
api_service_standalone  = { path = "../api_service_standalone" }
ledger = { path = "../../ledger" }
env_logger = "0.7.1"
ledger_app = { path = "../ledger_app" }
findora = { path = "../../findora" }
rand_chacha = "0.2.0"
rand_core = { version = "0.5", default-features = false, features = ["alloc"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
zei = { git = "ssh://git@github.com/findoraorg/zei" }

[dev-dependencies]
quickcheck = "0.8"
quickcheck_macros = "0.8"

