[package]
name = "ledger_standalone"
version = "0.1.0"
authors = ["Engineering <engineering@findora.org>"]
edition = "2018"

[[bin]]
name = "ledger_standalone"
path = "src/ledger_standalone.rs"

[dependencies]
findora = { path = "../../findora" }
env_logger = "0.7.1"
ledger_api_service = { path = "../ledger_api_service" }
ledger = { path = "../../ledger" }
rand_chacha = "0.2.0"
rand_core = { version = "0.5", default-features = false, features = ["alloc"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
submission_api = { path = "../submission_api" }
submission_server = { path = "../submission_server" }
zei = { git = "ssh://git@github.com/findoraorg/zei" }

[dev-dependencies]
quickcheck = "0.8"
quickcheck_macros = "0.8"

