[package]
name = "profiling"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pprof = { version = "0.11.1", features = ["flamegraph"] }
parking_lot = "0.12"
