[package]
name = "submission_api"
version = "0.1.0"
authors = ["Nathan Yospe <nathan@eian.io>"]
edition = "2018"

[lib]
path = "src/submission_api.rs"

[dependencies]
actix-cors = "0.1.0"
actix-rt = "0.2"
actix-service = "0.4.2"
actix-web = "1.0.5"
ledger = { path = "../../ledger" }
percent-encoding = "2.1.0"
submission_server = {path = "../submission_server"}
rand_core = { version = "0.5", default-features = false, features = ["alloc"] }
rand_chacha = "0.2.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
