[package]
name = "submission_api"
version = "0.1.0"
authors = ["Nathan Yospe <nathan@eian.io>"]
edition = "2018"
build = "build.rs"

[lib]
path = "src/submission_api.rs"

[dependencies]
ruc = { git = "https://github.com/FindoraNetwork/RUC.git", branch = "master" }
actix-cors = "0.5.4"
actix-rt = "1.1.0"
actix-service = "1.0.6"
actix-web = "3.3.2"
futures = "0.3"
parking_lot = "0.11.1"
ledger = { path = "../../ledger" }
log = "0.4.8"
percent-encoding = "2.1.0"
submission_server = {path = "../submission_server"}
rand_core = { version = "0.5", default-features = false, features = ["alloc"] }
rand_chacha = "0.2.0"
serde = "1.0.124"
serde_derive = "1.0"
serde_json = "1.0"
utils = { path = "../../libs/utils" }

[build-dependencies]
vergen = "=3.1.0"
