[package]
name = "txn_cli"
version = "0.1.0"
authors = ["Engineering <engineering@findora.org>"]
edition = "2018"
build = "build.rs"

[lib]
path = "src/lib.rs"

[[bin]]
name = "txn_cli"
path = "src/txn_cli.rs"

[dependencies]
clap = "2.33.0"
credentials = { path = "../../libs/credentials" }
curve25519-dalek = { version =  "2.0.0", features = ["serde"] }
cryptohash = { path = "../../libs/cryptohash" }
dirs = "2.0.2"
exitcode = "1.1.2"
flexi_logger = "0.15.2"
hex = "0.3.2"
ledger = { path = "../../ledger" }
ledger_standalone = { path = "../ledger_standalone" }
sparse_merkle_tree = { path = "../../libs/ads/sparse_merkle_tree" }
log = "0.4.8"
log-panics = {version ="2.0.0", features = ["with-backtrace"]}
network = { path = "../../libs/network" }
rand_chacha = "0.2.0"
rand_core = { version = "0.5", default-features = false, features = ["alloc"] }
reqwest = { version = "0.10", features = ["blocking", "json"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
shellexpand = "1.0.0"
submission_server = { path = "../submission_server" }
submission_api = { path = "../submission_api" }
ledger_api_service = { path = "../ledger_api_service" }
query_api = { path = "../query_api" }
tempfile = "3.1.0"
txn_builder = { path = "../txn_builder" }
utils = { path = "../../libs/utils", features = ["TESTING"] }
wasm = { path = "../wasm" }
zei = { git = "ssh://git@github.com/findoraorg/zei", tag = "v0.0.3-5" }

[dev-dependencies]
quickcheck = "0.8"
quickcheck_macros = "0.8"

[build-dependencies]
vergen = "3.1.0"

