[package]
name = "abci_validator_node"
version = "0.0.1"
authors = ["Engineering <engineering@findora.org>"]
edition = "2018"

[[bin]]
name = "abci_validator_node"
path = "src/abci_validator_node.rs"

[dependencies]
abci = "0.7.0"
ledger_api_service = { path = "../ledger_api_service" }
arrayref = "0.3.5"
ledger = { path = "../../ledger" }
log = "0.4.8"
cryptohash = { path = "../../libs/cryptohash" }
submission_server = { path = "../submission_server" }
rand_chacha = "0.2.0"
rand_core = { version = "0.5", default-features = false, features = ["alloc"] }
serde = { version = "1.0.99", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0.40"
zei = { git = "ssh://git@github.com/findoraorg/zei", tag = "v0.0.2-4" }
utils = { path = "../../libs/utils" }
