[package]
name = "fp-evm"
version = "0.1.0"
authors = ["Findora <admin@findora.org>"]
edition = "2018"
homepage = "https://findora.org/technology"
repository = "https://github.com/findoranetwork/platform/"
description = "Findora Primitive EVM abstractions types"
readme = "README.md"

[dependencies]
ethereum-types = "0.11.0"
evm = { version = "0.27.0", features = ["with-serde"] }
impl-trait-for-tuples = "0.2"
primitive-types = { version = "0.9.0", features = ["rlp", "byteorder", "serde"] }
ruc = { git = "https://github.com/FindoraNetwork/RUC.git", branch = "master" }
serde = { version = "1.0.124", features = ["derive"] }

# primitives
fp-core = { path = "../core" }
fp-types = { path = "../types" }
