[package]
name = "txn_builder_cli"
version = "0.1.0"
authors = ["Engineering <engineering@findora.org>"]
edition = "2018"

[[bin]]
name = "txn_builder_cli"
path = "src/txn_builder_cli.rs"

[dependencies]
clap = "2.33.0"
dirs = "2.0.2"
env_logger = "0.6.2"
findora = { path = "../../findora" }
ledger = { path = "../../ledger" }
submission_server = { path = "../submission_server" }
log = "0.4.8"
rand_chacha = "0.2.0"
rand_core = { version = "0.5", default-features = false, features = ["alloc"] }
reqwest = "0.9.24"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
shellexpand = "1.0.0"
txn_builder = { path = "../txn_builder" }
wasm = { path = "../wasm" }
zei = { git = "ssh://git@github.com/findoraorg/zei" }

[dev-dependencies]
quickcheck = "0.8"
quickcheck_macros = "0.8"

