[package]
name = "evm-precompile-abar"
version = "0.1.0"
edition = "2021"

[dependencies]
ethereum-types = { version = "0.14", default-features = false }
evm = { version = "0.35.0", default-features = false, features = ["with-serde"] }
evm-abar = { path = "../../../../primitives/abar" }
evm-precompile-utils = { path = "../utils"}
tracing = "0.1"
module-evm = { path = "../../../../modules/evm" }
num_enum = { version = "0.5.4", default-features = false }
platform-lib-noah = { git = "https://github.com/FindoraNetwork/platform-lib-noah", branch = "evm-abar" }

[dev-dependencies]
baseapp = { path = "../../../../baseapp" }
fp-mocks = { path = "../../../../primitives/mocks" }
ethereum-types = { version = "0.13.1", default-features = false }
hex = "0.4"