[package]
name = "evm-precompile-modexp"
version = "0.1.0"
authors = ["FindoraNetwork"]
edition = "2021"
homepage = "https://findora.org/technology"
repository = "https://github.com/findoranetwork/platform/"
description = "MODEXP precompiles for EVM module."
readme = "README.md"

[dependencies]
evm = { version = "0.35.0", default-features = false, features = ["with-serde"] }
module-evm = { path = "../../../../modules/evm"}
num = { version = "0.3", features = ["alloc"] }