[package]
name = "api_service"
version = "0.1.0"
authors = ["Nathan Yospe <nathan@eian.io>"]
edition = "2018"

[dependencies]
ledger = { path = "../../ledger" }
actix-web = "1.0"
actix-rt = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
rand_chacha = "0.1.1"
rand = "0.6"
