[package]
name = "whitelist_cli"
version = "0.1.0"
authors = ["Engineering <engineering@findora.org>"]
edition = "2018"

[[bin]]
name = "whitelist_cli"
path = "src/whitelist_cli.rs"

[dependencies]
clap = "2.33.0"
curve25519-dalek = { version =  "2.0.0", features = ["serde"] }
ledger = { path = "../../ledger" }
ledger_standalone = { path = "../ledger_standalone" }
# rand_chacha = "0.2"
# rand_core = { version = "0.5", default-features = false, features = ["alloc"] }
serde = "1.0"
serde_json = "1.0"
whitelist = { path = "../whitelist" }
zei = { git = "ssh://git@github.com/findoraorg/zei", tag = "v0.0.2-4" }