[package]
name = "wasm"
version = "0.1.0"
authors = ["ngolub <ngolub@stanford.edu>"]
edition = "2018"

[dependencies]
 bulletproofs = { version = "1.0.4",  package = "bulletproofs", git = "https://github.com/dalek-cryptography/bulletproofs", branch = "develop", features = ["yoloproofs"], rev = "3239bc9dd562bc8400f9054477c7c26c36974baf"}
cryptohash = { path = "../../libs/cryptohash" }
curve25519-dalek = { version =  "2.0.0", features = ["serde"] }
futures = "0.1.20"
hex = "0.3.2"
js-sys = "0.3.27"
ledger = { path = "../../ledger" }
percent-encoding = "2.1.0"
rand_chacha = "0.2.0"
rand_core = { version = "0.5", default-features = false, features = ["alloc"] }
serde = { version = "1.0.99", features = ["derive"] }
serde_derive = "^1.0.59"
serde_json = "1.0"
txn_builder = {path = "../txn_builder"}
wasm-bindgen = { version = "0.2.50", features = ["serde-serialize"]  }
wasm-bindgen-futures = "0.3.27"
wasm-bindgen-test = "0.2.50"
zei = { git = "ssh://git@github.com/findoraorg/zei" }

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/wasm.rs"

[dependencies.web-sys]
version = "0.3.4"
features = [
  'Headers',
  'Request',
  'RequestInit',
  'RequestMode',
  'Response',
  'Window',
]

[build-dependencies]
serde = "1.0.101"
serde_json = "1.0.41"
wasm-bindgen = { version = "0.2.50", features = ["serde-serialize"]  }

#features = ["stdweb", "wasm-bindgen"]
