[package]
name = "wasm"
version = "0.1.0"
authors = ["ngolub <ngolub@stanford.edu>"]
edition = "2018"

[dependencies]
bulletproofs =  {version = "1.0.4"}
<<<<<<< HEAD
curve25519-dalek = { version =  "1.2.1", features = ["serde"] }
futures = "0.1.20"
hex = "0.3.2"
js-sys = "0.3.27"
ledger = { path = "../../ledger" }
percent-encoding = "2.1.0"
rand = { version = "0.6", features = ["wasm-bindgen"] }
=======
serde_json = "1.0"
wasm-bindgen = { version = "0.2.50", features = ["serde-serialize"]  }
wasm-bindgen-test = "0.2.50"
>>>>>>> master
rand_chacha = "0.1.1"
serde = { version = "1.0.99", features = ["derive"] }
serde_derive = "^1.0.59"
serde_json = "1.0"
txn_builder = {path = "../txn_builder"}
wasm-bindgen = { version = "0.2.50", features = ["serde-serialize"]  }
wasm-bindgen-futures = "0.3.27"
wasm-bindgen-test = "0.2.50"
zei = { git = "ssh://git@github.com/findoraorg/zei" }

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/wasm.rs"

[dependencies.web-sys]
version = "0.3.4"
features = [
  'Headers',
  'Request',
  'RequestInit',
  'RequestMode',
  'Response',
  'Window',
]

[build-dependencies]
serde = "1.0.101"
serde_json = "1.0.41"
wasm-bindgen = { version = "0.2.50", features = ["serde-serialize"]  }
