[package]
name = "wasm"
version = "0.1.0"
authors = ["ngolub <ngolub@stanford.edu>"]
edition = "2018"
build = "build.rs"

# wasm-opt has a segfaulting issue. Disabling for now
[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[dependencies]
base64 = "0.10"
credentials = { path = "../../libs/credentials" }
cryptohash = { path = "../../libs/cryptohash" }
futures = "0.1.20"
hex = "0.3.2"
js-sys = "0.3.27"
ledger = { path = "../../ledger" }
rand_chacha = "0.2.0"
air = { path = "../../libs/ads/air" }
rand_core = { version = "0.5", default-features = false, features = ["alloc"] }
rand = { version = "0.7", features = ["wasm-bindgen"] }
serde = { version = "1.0.99", features = ["derive"] }
serde_derive = "^1.0.59"
serde_json = "1.0"
sparse_merkle_tree = { path = "../../libs/ads/sparse_merkle_tree" }
txn_builder = {path = "../txn_builder"}
wasm-bindgen = { version = "0.2.50", features = ["serde-serialize"]  }
wasm-bindgen-futures = "0.3.27"
wasm-bindgen-test = "0.2.50"
zei = { git = "ssh://git@github.com/FindoraNetwork/zei", branch = "fix-deps-v0.0.3-5" }
utils = { path = "../../libs/utils" }

ring = "0.16.19"
aes-gcm = "0.8.0"
bech32 = "0.7.2"

# Must enable the "js"-feature,
# OR the compiling will fail.
getrandom = { version = "0.2", features = ["js"] }

tiny-bip39 = "0.8.0"
ed25519-dalek-bip32 = "0.1.1"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/wasm.rs"

[dependencies.web-sys]
version = "0.3.4"
features = [
  'Headers',
  'Request',
  'RequestInit',
  'RequestMode',
  'Response',
  'Window',
  'console',
]

[build-dependencies]
serde = "1.0.101"
serde_json = "1.0.41"
vergen = "3.1.0"
wasm-bindgen = { version = "0.2.50", features = ["serde-serialize"]  }

[dev-dependencies]
# Must enable the "js"-feature,
# OR the compiling will fail.
getrandom = { version = "0.2", features = ["js"] }
