[package]
name = "solvency_cli"
version = "0.1.0"
authors = ["Engineering <engineering@findora.org>"]
edition = "2018"

[[bin]]
name = "solvency_cli"
path = "src/solvency_cli.rs"

[dependencies]
clap = "2.33.0"
hex = "0.3.2"
ledger = { path = "../../ledger" }
ledger_standalone = { path = "../ledger_standalone" }
rand_chacha = "0.2"
rand_core = { version = "0.5", default-features = false, features = ["alloc"] }
serde = "1.0"
serde_json = "1.0"
solvency = { path = "../solvency" }
zei = { git = "ssh://git@github.com/findoraorg/zei", tag = "v0.0.2-4" }