[package]
name = "findora"
version = "0.1.0"
authors = ["Jonathan Bertoni <jonathan@eian.io>"]
edition = "2018"

[lib]
path = "src/findora.rs"

[dependencies]
bincode = "1.0"
byteorder = "1.0"
chrono = "0.4"
protobuf = "1.7.5"
serde = "1.0"
serde_derive = "1.0"
