[package]
name = "evm-precompile-utils"
version = "0.1.0"
authors = ["PureStake"]
edition = "2021"
description = "Utils to write EVM precompiles."

[dependencies]
ethereum = { version = "0.14.0", default-features = false, features = ["with-serde"] }
ethereum-types = { version = "0.13.1", default-features = false }
evm = { version = "0.35.0", default-features = false, features = ["with-serde"] }
tracing = "0.1"
num_enum = { version = "0.5.3", default-features = false }
precompile-utils-macro = { path = "macro" }
sha3 = { version = "0.8", default-features = false }
