[package]
name = "wasm"
version = "0.2.11"
authors = ["FindoraNetwork"]
build = "build.rs"
edition = "2021"

description = ""
repository = ""
license = ""

# wasm-opt has a segfaulting issue. Disabling for now
[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[dependencies]
base64 = "0.13"
hex = "0.4.2"
js-sys = "0.3.27"
rand_chacha = "0.3"
rand_core = { version = "0.6", default-features = false, features = ["alloc"] }
rand = { version = "0.7", features = ["wasm-bindgen"] }
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0"
wasm-bindgen = { version = "=0.2.73", features = ["serde-serialize"] }

ring = "0.16.19"
aes-gcm = "0.9.0"
bech32 = "0.9.1"

# Must enable the "js"-feature,
# OR the compiling will fail.
getrandom = { version = "0.2", features = ["js"] }

zei = { git = "https://github.com/FindoraNetwork/zei", tag = "v0.1.4x" }
ruc = "1.0"

finutils = { path = "../finutils", default-features = false }
globutils = { path = "../../libs/globutils" }
credentials = { path = "../../libs/credentials" }
cryptohash = { path = "../../libs/cryptohash" }
ledger = { path = "../../ledger" }

fp-utils = { path = "../contracts/primitives/utils" }
fp-types = { path = "../contracts/primitives/types" }

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/wasm.rs"

[dependencies.web-sys]
version = "0.3.4"
features = [
  'Headers',
  'Request',
  'RequestInit',
  'RequestMode',
  'Response',
  'Window',
  'console',
]

[build-dependencies]
serde = "1.0.124"
serde_json = "1.0.41"
vergen = "=3.1.0"
wasm-bindgen = { version = "=0.2.73", features = ["serde-serialize"] }

[dev-dependencies]
# Must enable the "js"-feature,
# OR the compiling will fail.
getrandom = { version = "0.2", features = ["js"] }
