[package]
name = "wasm"
version = "0.2.11"
authors = ["FindoraNetwork"]
build = "build.rs"
edition = "2021"

description = ""
repository = ""
license = ""

[features]
lightweight = ["noah/lightweight"] # Minimize size for only AR2ABAR and ABAR2AR.

# wasm-opt has a segfaulting issue. Disabling for now
[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[dependencies]
base64 = "0.13"
hex = "0.4.2"
js-sys = "0.3.27"
rand_chacha = "0.3"
rand_core = { version = "0.6", default-features = false, features = ["alloc"] }
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0"
wasm-bindgen = { version = "0.2.83", features = ["serde-serialize"] }
bs58 = "0.4"

ring = "0.16.19"
aes-gcm = '=0.10.0-pre'
bech32 = "0.7.2"
ruc = "1.0"

# Must enable the "js"-feature,
# OR the compiling will fail.
getrandom = { version = "0.2", features = ["js"] }

noah = "0.2"
noah-algebra = "0.2"
noah-crypto = "0.2"

finutils = { path = "../finutils", default-features = false }
globutils = { path = "../../libs/globutils" }
credentials = { path = "../../libs/credentials" }
cryptohash = { path = "../../libs/cryptohash" }
ledger = { path = "../../ledger" }

fp-utils = { path = "../contracts/primitives/utils" }
fp-types = { path = "../contracts/primitives/types" }

fbnc = { version = "0.2.9", default-features = false}

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/wasm.rs"

[dependencies.web-sys]
version = "0.3.4"
features = [
  'Headers',
  'Request',
  'RequestInit',
  'RequestMode',
  'Response',
  'Window',
  'console',
]

[build-dependencies]
serde = "1.0.124"
serde_json = "1.0.41"
vergen = "=3.1.0"
wasm-bindgen = { version = "0.2.83", features = ["serde-serialize"] }

[dev-dependencies]
# Must enable the "js"-feature,
# OR the compiling will fail.
getrandom = { version = "0.2", features = ["js"] }
wasm-bindgen-test = "0.3.0"
