[package]
name = "wasm"
version = "0.2.11"
authors = ["FindoraNetwork"]
build = "build.rs"
edition = "2021"

description = ""
repository = ""
license = ""

# wasm-opt has a segfaulting issue. Disabling for now
[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[dependencies]
base64 = "0.13"
hex = "0.4.2"
js-sys = "0.3.27"
rand_chacha = "0.3"
rand_core = { version = "0.6", default-features = false, features = ["alloc"] }
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0"
wasm-bindgen = { version = "=0.2.84", features = ["serde-serialize"] }
fbnc = { version = "0.2.9", default-features = false}

ring = "0.16.19"
aes-gcm = '^0.10.1'
bech32 = "0.7.2"
ruc = "1.0"
bs58 = "0.4"

# Must enable the "js"-feature,
# OR the compiling will fail.
getrandom = { version = "0.2", features = ["js"] }

noah  = { git = "https://github.com/FindoraNetwork/noah", tag = "v0.4.3" }
noah-algebra  = { git = "https://github.com/FindoraNetwork/noah", tag = "v0.4.3" }
noah-crypto  = { git = "https://github.com/FindoraNetwork/noah", tag = "v0.4.3" }

finutils = { path = "../finutils", default-features = false }
globutils = { git = "https://github.com/shaorongqiang/platform-lib-utils", branch = "main" }
credentials = { git = "https://github.com/shaorongqiang/platform-lib-credentials", branch = "main" }
cryptohash = { git = "https://github.com/shaorongqiang/platform-lib-cryptohash", branch = "main" }
ledger = { path = "../../ledger" }


fp-utils = { path = "../contracts/primitives/utils" }
fp-types = { path = "../contracts/primitives/types" }
zei = { package="platform-lib-noah", git = "https://github.com/FindoraNetwork/platform-lib-noah", branch = "main" }

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/wasm.rs"

[dependencies.web-sys]
version = "0.3.4"
features = [
  'Headers',
  'Request',
  'RequestInit',
  'RequestMode',
  'Response',
  'Window',
  'console',
]

[build-dependencies]
serde = "1.0.124"
serde_json = "1.0.41"
vergen = "=3.1.0"
wasm-bindgen = { version = "=0.2.84", features = ["serde-serialize"] }

[dev-dependencies]
# Must enable the "js"-feature,
# OR the compiling will fail.
getrandom = { version = "0.2", features = ["js"] }
wasm-bindgen-test = "0.3.0"

[features]
lightweight = ["noah/lightweight"] # Minimize size for only AR2ABAR and ABAR2AR.
