[package]
name = "solvency"
version = "0.1.0"
authors = ["Engineering <engineering@findora.org>"]
edition = "2018"

[lib]
path = "src/solvency.rs"

[dependencies]
bulletproofs = { package = "bulletproofs", git = "ssh://git@github.com/findoraorg/bulletproofs", branch = "batch_verification", features = ["yoloproofs"] }
curve25519-dalek = { version =  "2.0.0", features = ["serde"] }
ledger = { path = "../../ledger" }
ledger_api_service = { path = "../ledger_api_service" }
ledger_standalone = { path = "../ledger_standalone" }
linear-map = "1.2.0"
network = { path = "../../libs/network" }
rand_chacha = "0.2"
rand_core = { version = "0.5", default-features = false, features = ["alloc"] }
reqwest = "0.9.24"
serde = "1.0"
serde_json = "1.0"
submission_server = { path = "../submission_server" }
txn_builder = { path = "../txn_builder" }
txn_cli = { path = "../txn_cli" }
zei = { git = "ssh://git@github.com/findoraorg/zei", tag = "v0.0.3-2" }
