[package]
name = "solvency"
version = "0.1.0"
authors = ["Engineering <engineering@findora.org>"]
edition = "2018"

[lib]
path = "src/solvency.rs"

[dependencies]
bulletproofs = { version = "2.0.0",  package = "bulletproofs", git = "https://github.com/dalek-cryptography/bulletproofs", rev = "91218d4066af5d582631319c5ff0266402b9fff2", features = ["yoloproofs"]}
curve25519-dalek = { version =  "2.0.0", features = ["serde"] }
hex = "0.3.2"
ledger = { path = "../../ledger" }
ledger_standalone = { path = "../ledger_standalone" }
linear-map = "1.2.0"
rand_chacha = "0.2"
rand_core = { version = "0.5", default-features = false, features = ["alloc"] }
reqwest = "0.9.24"
serde = "1.0"
serde_json = "1.0"
submission_server = { path = "../submission_server" }
txn_builder = { path = "../txn_builder" }
zei = { git = "ssh://git@github.com/findoraorg/zei", tag = "v0.0.2-4" }