[package]
name = "evm-abar"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3"
ethereum-types = { version = "0.14", default-features = false }
platform-lib-noah = { git = "https://github.com/FindoraNetwork/platform-lib-noah", branch = "evm-abar" }
rand_core = { version = '0.6', default-features = false, features = ['alloc'] }
ruc = "1.0"
serde = { version = "1.0", features = ["derive"] }