[package]
name = "address_identity_registry"
version = "0.0.1"
authors = ["Engineering <engineering@findora.org>"]
edition = "2018"

[[bin]]
name = "repl"
path = "src/bin/repl.rs"

[[bin]]
name = "generate_txns"
path = "src/bin/generate_txns.rs"

[[bin]]
name = "user"
path = "src/bin/user.rs"

[[bin]]
name = "issuer"
path = "src/bin/issuer.rs"

[[bin]]
name = "verifier"
path = "src/bin/verifier.rs"

[dependencies]
ruc = "0.5.5"
air = { path = "../../../libs/ads/air" }
async-std = "1.5.0"
clap = "2.33.0"
colored = "1.9"
credentials = { path = "../../../libs/credentials" }
cryptohash = { path = "../../../libs/cryptohash" }
flexi_logger = "0.15.2"
futures = "0.3.1"
hex = "0.3.2"
lazy_static = { version = "1.2.0" }
ledger = { path = "../../../ledger" }
ledger_standalone = { path = "../../ledger_standalone" }
linear-map = {version = "1.2.0", features = ["serde_impl"] }
log = "0.4.8"
rmp-serde = "0.13.7"
rand_chacha = "0.2.0"
rand_core = { version = "0.5", default-features = false, features = ["alloc"] }
reqwest = { version = "0.10", default-features = false, features = ["rustls-tls", "blocking", "json"] }
rustyline = "6.0.0"
serde = { version = "1.0.99", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0.40"
sha2 = "0.8.0"
submission_server = { path = "../../submission_server" }
tokio = { version = "0.2", features = ["full", "macros"] }
txn_builder = { path = "../../txn_builder" }
utils = { path = "../../../libs/utils" }
warp = "0.2"
zei = { git = "ssh://git@github.com/FindoraNetwork/zei", tag = "v0.1.0b" }
