[package]
name = "evm-precompile-sha3fips"
version = "0.1.0"
authors = ["FindoraNetwork"]
edition = "2021"
homepage = "https://findora.org/technology"
repository = "https://github.com/findoranetwork/platform/"
description = "SHA3 FIPS202 precompiles for EVM module."
readme = "README.md"

[dependencies]
evm = { version = "0.37.0", default-features = false, features = ["with-serde"] }
module-evm = { path = "../../../../modules/evm"}
tiny-keccak = { version = "2.0", features = ["fips202"] }
