[package]
name = "fp-traits"
version = "0.1.0"
authors = ["FindoraNetwork"]
edition = "2021"
homepage = "https://findora.org/technology"
repository = "https://github.com/findoranetwork/platform/"
description = "Findora Primitive Trait definitions for all module interactions"
readme = "README.md"

[dependencies]
ethereum = { version = "0.12.0", default-features = false, features = ["with-serde"] }
primitive-types = { version = "0.12.0", default-features = false, features = ["rlp", "byteorder", "serde"] }
ruc = "1.0"

# primitives
fp-core = { path = "../core" }
fp-evm = { path = "../evm" }
fp-types = { path = "../types" }