[package]
name = "evm-precompile-frc20"
version = "0.1.0"
authors = ["FindoraNetwork"]
edition = "2021"
homepage = "https://findora.org/technology"
repository = "https://github.com/findoranetwork/platform/"
description = "FRC20 precompiles for EVM module."
readme = "README.md"

[dependencies]
ethereum-types = { version = "0.13.1", default-features = false }
evm = { version = "0.35.0", default-features = false, features = ["with-serde"] }
evm-precompile-utils = { path = "../utils"}
fp-traits = { path = "../../../../primitives/traits" }
tracing = "0.1"
module-evm = { path = "../../../../modules/evm"}
num_enum = { version = "0.6.0", default-features = false }
slices = "0.2.0"
config = { path = "../../../../../config" }

[dev-dependencies]
baseapp = { path = "../../../../baseapp" }
fp-mocks = { path = "../../../../primitives/mocks" }
sha3 = "0.10"