[package]
name = "module-xhub"
version = "0.1.0"
authors = ["FindoraNetwork"]
edition = "2021"
homepage = "https://findora.org/technology"
repository = "https://github.com/findoranetwork/platform/"
description = "UTXO and Account state transit hub"
readme = "README.md"

[dependencies]
abci = { git = "https://github.com/FindoraNetwork/tendermint-abci", tag = "0.7.4" }
lazy_static = "1.4.0"
ledger = { path = "../../../../ledger" }
log = "0.4"
primitive-types = { version = "0.10.0", default-features = false, features = ["rlp", "byteorder", "serde"] }
ruc = "1.0"
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0"

# primitives, don't depend on any modules
fp-core = { path = "../../primitives/core" }
fp-storage = { path = "../../primitives/storage" }
fp-traits = { path = "../../primitives/traits" }
fp-types = { path = "../../primitives/types" }

[dev-dependencies]
fp-mocks = { path = "../../primitives/mocks" }
