[package]
name = "frog"
version = "0.2.9"
authors = ["FindoraNetwork"]
build = "build.rs"
edition = "2018"

[dependencies]
attohttpc = { version = "0.18", default-features = false, features = ["compress", "json", "tls-rustls"] }
serde_json = "1.0.40"
serde = { version = "1.0.124", features = ["derive"] }
rand = "0.8"
zei = { git = "https://github.com/FindoraNetwork/zei", tag = "v0.1.4e" }
ruc = "0.6.6"
ledger = { path = "../../ledger" }
finutils = { path = "../finutils" }
globutils = { path = "../../libs/globutils" }

[build-dependencies]
ruc = "0.6.6"
vergen = "=3.1.0"
serde_json = "1.0.40"
ledger = { path = "../../ledger" }
globutils = { path = "../../libs/globutils" }
zei = { git = "https://github.com/FindoraNetwork/zei", tag = "v0.1.4e" }
attohttpc = { version = "0.18", default-features = false, features = ["compress", "json", "tls-rustls"] }

[[bin]]
name = "gendtx"
path = "src/bins/gendtx/gendtx.rs"

# [[bin]]
# name = "genutx"
# path = "src/bins/genutx/genutx.rs"
