[package]
name = "evm-precompile"
version = "0.1.0"
authors = ["FindoraNetwork"]
edition = "2021"
homepage = "https://findora.org/technology"
repository = "https://github.com/findoranetwork/platform/"
description = "MODEXP precompiles for EVM module."
readme = "README.md"

[dependencies]
evm = { version = "0.35.0", default-features = false, features = ["with-serde"] }
module-evm = { path = "../../../modules/evm"}
ethereum-types = "0.13.1"
evm-precompile-basic = { path = "./basic" }
evm-precompile-sha3fips = {path = "./sha3fips" }
evm-precompile-modexp = { path = "./modexp" }
evm-precompile-frc20 = { path = "./frc20" }
evm-precompile-eth-pairings = { path = "./eth-pairings" }
storage = { git = "https://github.com/FindoraNetwork/storage.git", tag = "v0.2.2" }
fp-core = { path = "../../../primitives/core" }
parking_lot = "0.12"
fin_db = { git = "https://github.com/FindoraNetwork/storage.git", tag = "v0.2.2" }
