[package]
name = "eth-pairings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eth_pairings = { git = "https://github.com/FindoraNetwork/eip1962", branch = "master" }