[package]
name = "ledger_client"
version = "0.1.0"
authors = ["Engineering <engineering@findora.org>"]
edition = "2018"

[[bin]]
name = "ledger_client"
path = "src/ledger_client.rs"

[dependencies]
ruc = { git = "https://github.com/FindoraNetwork/RUC.git", branch = "master" }
arrayref = "0.3.5"
cryptohash = { path = "../../libs/cryptohash" }
ledger = { path = "../../ledger" }
percent-encoding = "2.1.0"
rand_chacha = "0.2.0"
rand_core = { version = "0.5", default-features = false, features = ["alloc"] }
attohttpc = { version = "0.16.3", default-features = false, features = ["compress", "json", "tls-rustls"] }
serde = "1.0.124"
serde_derive = "1.0"
serde_json = "1.0"
utils = { path = "../../libs/utils" }
zei = { git = "ssh://git@github.com/FindoraNetwork/zei", tag = "v0.1.0d" }

[dev-dependencies]
quickcheck = "0.8"
quickcheck_macros = "0.8"

