[package]
name = "address_identity_registry"
version = "0.0.1"
authors = ["Engineering <engineering@findora.org>"]
edition = "2018"

[[bin]]
name = "address_identity_registry"
path = "src/address_identity_registry.rs"

[dependencies]
hex = "0.3.2"
serde = { version = "1.0.99", features = ["derive"] }
serde_json = "1.0.40"
rmp-serde = "0.13.7"
clap = "2.33.0"
sha2 = "0.8.0"
rand_chacha = "0.2.0"
rand_core = { version = "0.5", default-features = false, features = ["alloc"] }
log = "0.4.8"
env_logger = "0.6.2"
zei = { git = "ssh://git@github.com/findoraorg/zei" }
