[package]
name = "query_server"
version = "0.1.0"
authors = ["Nathan Yospe <nathan@eian.io>"]
edition = "2018"

[lib]
path = "src/query_server.rs"

[dependencies]
ledger = { path = "../../ledger" }
ledger_standalone = {path = "../ledger_standalone"}
log = "0.4.8"
ledger_api_service  = { path = "../../components/ledger_api_service" }
rand_chacha = "0.2.0"
rand_core = { version = "0.5", default-features = false, features = ["alloc"] }
reqwest = "0.9.24"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
sparse_merkle_tree = { path = "../../libs/ads/sparse_merkle_tree" }
txn_builder = {path = "../txn_builder"}
zei = { git = "ssh://git@github.com/findoraorg/zei", tag = "v0.0.3-3" }
