[package]
name = "query_server"
version = "0.1.0"
authors = ["Nathan Yospe <nathan@eian.io>"]
edition = "2018"

[lib]
path = "src/query_server.rs"

[dependencies]
ruc = { git = "https://github.com/FindoraNetwork/RUC.git", branch = "master" }
parking_lot = "0.11.1"

ledger = { path = "../../ledger" }
log = "0.4.8"
ledger_api_service  = { path = "../../components/ledger_api_service" }
rand_chacha = "0.2.0"
rand_core = { version = "0.5", default-features = false, features = ["alloc"] }
serde = "1.0.124"
serde_derive = "1.0"
serde_json = "1.0"
sparse_merkle_tree = { path = "../../libs/ads/sparse_merkle_tree" }
txn_builder = {path = "../txn_builder"}
utils = { path = "../../libs/utils" }
zei = { git = "ssh://git@github.com/FindoraNetwork/zei", tag = "v0.1.3a" }
lazy_static = "1.4.0"
metrics-exporter-prometheus = "0.2.0"

[features]
debug_env = [ "ledger/debug_env" ]