name: FN
on:
  push:
    tags:
      - '*-fn'
    # branches:
    #   - "add-fn-build"
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    strategy:
      matrix:
        platform: [scalable]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt
        

    # - name: Build fn for Linux 
    #   shell: bash
    #   run: |
    #     make build_musl_fn_linux

    # - name: Build environment for Macos 
    #   shell: bash
    #   run: |
    #     make build_musl_fn_macos_base

    # - name: Build fn for Macos 
    #   shell: bash
    #   run: |
    #     make build_musl_fn_macos

    - name: prepare the tag infomation
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: |
        echo "REF: ${GITHUB_REF}"
        TAGS=$(grep "refs/tags" <<< ${GITHUB_REF}) || true
        export TAGV="${TAGS#refs/tags/}"
        echo "Tag: ${TAGV}"

    - name: Create release
      uses: "marvinpinto/action-automatic-releases@latest"

      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: ${TAGV}
        # files: |
        #   fn
        #   fn_macos
