name: FN
on:
  push:
    # tags:
    #   - '*-fn'
    branches:
      - "add-fn-build"
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    strategy:
      matrix:
        platform: [scalable]
    runs-on: ${{ matrix.platform }}
    env:
      ENV: dev
      PRIVATE_ECR_URL: 358484141435.dkr.ecr.us-west-2.amazonaws.com
      PUBLIC_ECR_URL: public.ecr.aws/k6m5b6e2
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt
        
    # - name: Prepare key
    #   shell: bash
    #   run: |
    #     tar -C ~/.ssh -zcf key.tar.gz ./
        
    # - name: Build fn for Linux 
    #   shell: bash
    #   run: |
    #     make build_musl_fn_linux

    - name: Build fn for Macos 
      shell: bash
      run: |
        make build_musl_fn_macos

    - name: Create release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "test-release"
        files: |
          fn



