name: Wasm Building And Pushing
on:
  push:
    branches: ['**']

jobs:
  build-push:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Rust enviroment
        uses: actions-rs/toolchain@v1
        with: 
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
          profile: minimal

      - name: Install Wasm-pack
        # install wasm-pack from downloading is more faster then cargo install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh


      - name: Checkout platform branch
        uses: actions/checkout@v2

      - name: Using cache to speed up
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
      - name: Building WASM
        id: wasm
        run: |
          # print out the script steps
          set -x
          # make a unique temp folder for storing output
          tmp=$( mktemp -d )
          # set some vars for further usage
          echo "::set-output name=tmp::${tmp}"
          echo "::set-output name=sha::$(git rev-parse --short HEAD)"
          echo "::set-output name=date::$(date +'%Y-%m-%d')"
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

          cd ./src/components/wasm
          wasm-pack build --release --target nodejs --out-dir $tmp/nodejs
          wasm-pack build --release --target web --out-dir $tmp/web
          wasm-pack build --release --target bundler --out-dir $tmp/bundler

      - name: Pushing wasm-js-bindings branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: FindoraNetwork/wasm-js-bindings
          branch: ${{ steps.wasm.outputs.branch }}
          folder: ${{ steps.wasm.outputs.tmp }}
          token: ${{ secrets.ACCESS_TOKEN }}
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          git-config-name: wasmcat-bot
          git-config-email: wasmcat-bot@users.noreply.github.com
          clean-exclude: |
            .gitignore
            .DS_Store
            LICENSE
          commit-message: >
            From platform branch: ${{ steps.wasm.outputs.branch }}
            commit hash ${{ steps.wasm.outputs.sha }}
            date: ${{ steps.wasm.outputs.date }}
