name: Wasm Building And Pushing
on:
  push:
    branches: ['**']

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Rust enviroment
        uses: actions-rs/toolchain@v1
        with: 
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
          profile: minimal

      - name: Install Wasm-pack
        # install wasm-pack from downloading is more faster then cargo install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh


      - name: Checkout platform branch
        uses: actions/checkout@v2

      - name: Using cache to speed up
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
      - name: Building WASM
        run: |
          # print out the script steps
          set -x
          # make a unique temp folder for storing output
          tmp=$( mktemp -d )

          cd ./src/components/wasm
          wasm-pack build --release --target nodejs --out-dir $tmp/nodejs
          wasm-pack build --release --target web --out-dir $tmp/web
          wasm-pack build --release --target bundler --out-dir $tmp/bundler

          ls -la $tmp

      - name: Debugging
        run: |
          # testing: 
          set -x
          ls $GITHUB_WORKSPACE

      - name: Checkout wasm-js-bindings branch
        uses: actions/checkout@v2
        with:
          repository: FindoraNetwork/wasm-js-bindings
          # ref: testing_wasm_cat # change to ${{ github.ref }} later
          
      - name: Debugging
        run: |
          # testing: 
          set -x
          ls $GITHUB_WORKSPACE
