name: Wasm Building And Pushing
on:
  push:
    branches: ['**']

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Rust enviroment
        uses: actions-rs/toolchain@v1
        with: 
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
          profile: minimal

      - name: Install Wasm-pack
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: wasm-pack

      - name: Checkout platform branch
        uses: actions/checkout@v2
    
      - name: Building WASM
        run: |
          # print out the script steps
          set -x
          # make a unique temp folder for storing output
          tmp=$( mktemp -d )

          # testing: 
          ls $(which cargo)
          echo the work place: $GITHUB_WORKSPACE
          echo the temp place: $tmp
          ls $GITHUB_WORKSPACE

          # - name: Checkout wasm-js-bindings branch
          #   uses: actions/checkout@v2
          #   with:
          #     repository: FindoraNetwork/wasm-js-bindings
          #     # ref: testing_wasm_cat # change to ${{ github.ref }} later
