name: Wasm Building And Pushing
on: [push]

jobs:
  build-push:
    concurrency: wasm-ci-${GITHUB_REF##*/}
    runs-on: ubuntu-latest
    # accepting any branches push but not pull_request
    if: github.event_name != 'pull_request'
    steps:
      - name: Setup Rust enviroment
        uses: actions-rs/toolchain@v1
        with: 
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
          profile: minimal

      - name: Install Wasm-pack
        # install wasm-pack from downloading is more faster then cargo install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Checkout platform branch
        uses: actions/checkout@v2
        with:
          path: platform

      - name: Checkout wasm-js-bindings branch
        uses: actions/checkout@v2
        with:
          repository: FindoraNetwork/wasm-js-bindings
          ref: ${{ github.ref }}
          token: ${{ secrets.ACCESS_TOKEN }}
          path: wasm-js-bindings

      - name: Using cache to speed up
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
      - name: Building WASM
        id: wasm
        run: |
          ## print out the script steps
          #set -x
          ## make a unique temp folder for storing output
          #tmp=$( mktemp -d )
          # set some vars for further usage
          # echo "::set-output name=tmp::${tmp}"
          echo "::set-output name=sha::$(git rev-parse --short HEAD)"
          echo "::set-output name=date::$(date +'%Y-%m-%d')"
          echo "::set-output name=branch::$(echo ${GITHUB_REF##*/})"

          cd platform/src/components/wasm
          wasm-pack build --release --target nodejs --out-dir ${GITHUB_WORKSPACE}/wasm-js-bindings/nodejs
          wasm-pack build --release --target web --out-dir ${GITHUB_WORKSPACE}/wasm-js-bindings/web
          wasm-pack build --release --target bundler --out-dir ${GITHUB_WORKSPACE}/wasm-js-bindings/bundler

      - name: Pushing wasm-js-bindings branch
        run: |
          cd ${GITHUB_WORKSPACE}/wasm-js-bindings
          git add .
          git config user.name wasmcat-bot
          git config user.email wasmcat-bot@users.noreply.github.com
          git commit -am "platform (${{ steps.wasm.outputs.branch }}:${{ steps.wasm.outputs.sha }}) by wasmcat-bot automation push 🚀"
          git push

        # uses: dmnemec/copy_file_to_another_repo_action@main
        # env:
        #   API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN }}
        # with:
        #   destination_repo: 'FindoraNetwork/wasm-js-bindings'
        #   destination_branch: ${{ steps.wasm.outputs.branch }}
        #   destination_branch_create: ${{ steps.wasm.outputs.branch }}
        #   source_file: '${{ steps.wasm.outputs.tmp }}'
        #   user_name: wasmcat-bot
        #   user_email: wasmcat-bot@users.noreply.github.com
        #   commit_message: 'platform (${{ steps.wasm.outputs.branch }}:${{ steps.wasm.outputs.sha }}) by wasmcat-bot automation push 🚀'
            # - name: Pushing wasm-js-bindings branch
            #   uses: JamesIves/github-pages-deploy-action@v4.2.2
            #   with:
            #     repository-name: FindoraNetwork/wasm-js-bindings
            #     branch: ${{ steps.wasm.outputs.branch }}
            #     folder: ${{ steps.wasm.outputs.tmp }}
            #     token: ${{ secrets.ACCESS_TOKEN }}
            #     ssh-key: ${{ secrets.DEPLOY_KEY }}
            #     git-config-name: wasmcat-bot
            #     git-config-email: wasmcat-bot@users.noreply.github.com
            #     clean-exclude: |
            #       .gitignore
            #       .DS_Store
            #       LICENSE
            #     commit-message: "platform <${{ steps.wasm.outputs.branch }}>(${{ steps.wasm.outputs.sha }}) by wasmcat-bot automation push 🚀"
