[package]
name = "xfrnote"
version = "0.1.0"
authors = ["Engineering <engineering@findora.org>"]
edition = "2018"

[[bin]]
name = "xfrnote"
path = "src/bin/xfrnote.rs"

[dependencies]
ruc = { git = "https://github.com/FindoraNetwork/RUC.git", branch = "master" }
async-std = "1.5.0"
flexi_logger = "0.15.2"
futures = "0.3"
itertools = "0.8.0"
json = "0.12.4"
ledger = { path = "../../../ledger" }
libp2p = "0.24.0"
log = "0.4.8"
names = "0.11.0"
rand_chacha = "0.2.0"
rand_core = { version = "0.5", default-features = false, features = ["alloc"] }
serde = { version = "1.0.124", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0.40"
tokio = { version = "0.2", features = ["full", "macros"] }
tokio-codec = "0.1.2"
zei = { git = "ssh://git@github.com/FindoraNetwork/zei", tag = "v0.1.0d" }
